"""
PharmaInsight AI — Demand Forecasting Dashboard

Interactive business dashboard built from validated forecasting outputs.

The dashboard does not train models or modify forecasts.
It reads the finalized reports generated by the forecasting pipeline.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd
import plotly.graph_objects as go
import streamlit as st


# ============================================================================
# CONFIGURATION
# ============================================================================

PROJECT_ROOT = Path(__file__).resolve().parent.parent

CATEGORY_FILE = (
    PROJECT_ROOT
    / "reports"
    / "dashboard"
    / "category_summary.csv"
)

DAILY_FILE = (
    PROJECT_ROOT
    / "reports"
    / "dashboard"
    / "forecast_daily.csv"
)

SUMMARY_FILE = (
    PROJECT_ROOT
    / "reports"
    / "dashboard"
    / "dashboard_summary.csv"
)


st.set_page_config(
    page_title="PharmaInsight AI",
    page_icon="💊",
    layout="wide",
)


# ============================================================================
# DATA LOADING
# ============================================================================

@st.cache_data
def load_data():
    """Load validated dashboard data."""

    category = pd.read_csv(CATEGORY_FILE)
    daily = pd.read_csv(DAILY_FILE)
    summary = pd.read_csv(SUMMARY_FILE)

    required_category = {
        "category",
        "model",
        "recent_30d_mean",
        "forecast_30d_mean",
        "forecast_change_pct",
        "MASE",
        "status",
    }

    required_daily = {
        "datum",
        "category",
        "model",
        "forecast",
    }

    required_summary = {
        "total_categories",
        "flagged_categories",
        "forecast_horizon_days",
        "total_forecast_demand",
        "total_recent_30d_demand",
        "overall_change_pct",
        "best_mase_category",
        "best_mase_model",
        "model_counts",
    }

    missing_category = required_category - set(category.columns)
    missing_daily = required_daily - set(daily.columns)
    missing_summary = required_summary - set(summary.columns)

    if missing_category:
        raise ValueError(
            f"Missing category-summary columns: {sorted(missing_category)}"
        )

    if missing_daily:
        raise ValueError(
            f"Missing forecast-daily columns: {sorted(missing_daily)}"
        )

    if missing_summary:
        raise ValueError(
            f"Missing dashboard-summary columns: {sorted(missing_summary)}"
        )

    daily["datum"] = pd.to_datetime(daily["datum"])

    return category, daily, summary


try:
    category_df, daily_df, dashboard_summary = load_data()

except FileNotFoundError as exc:
    st.error(
        "Dashboard data files were not found.\n\n"
        "Run:\n\n"
        "`python -m ml.forecasting.build_dashboard_data`"
    )
    st.exception(exc)
    st.stop()

except ValueError as exc:
    st.error("Dashboard data schema validation failed.")
    st.exception(exc)
    st.stop()


# ============================================================================
# HEADER
# ============================================================================

st.markdown(
    """
    <h1 style="margin-bottom:0;">
        💊 PharmaInsight AI
    </h1>
    """,
    unsafe_allow_html=True,
)

st.markdown(
    """
    <p style="font-size:1.1rem; color:#6b7280;">
        Pharmaceutical Demand Forecasting & Business Analytics
    </p>
    """,
    unsafe_allow_html=True,
)


# ============================================================================
# GLOBAL KPIs
# ============================================================================

summary_row = dashboard_summary.iloc[0]

total_categories = int(summary_row["total_categories"])
flagged_categories = int(summary_row["flagged_categories"])
forecast_horizon = int(summary_row["forecast_horizon_days"])

total_forecast = float(
    summary_row["total_forecast_demand"]
)

total_recent = float(
    summary_row["total_recent_30d_demand"]
)

overall_change = float(
    summary_row["overall_change_pct"]
)

best_category = str(
    summary_row["best_mase_category"]
)

best_model = str(
    summary_row["best_mase_model"]
)


col1, col2, col3, col4, col5 = st.columns(5)

with col1:
    st.metric(
        "Product Categories",
        total_categories,
    )

with col2:
    st.metric(
        "Forecast Horizon",
        f"{forecast_horizon} days",
    )

with col3:
    st.metric(
        "Overall Forecast Change",
        f"{overall_change:+.1f}%",
    )

with col4:
    st.metric(
        "Categories Flagged",
        flagged_categories,
    )

with col5:
    st.metric(
        "Best MASE",
        best_category,
        delta=best_model,
    )


st.divider()


# ============================================================================
# SIDEBAR
# ============================================================================

st.sidebar.header("Dashboard Controls")

categories = sorted(
    category_df["category"].astype(str).unique()
)

selected_category = st.sidebar.selectbox(
    "Select product category",
    categories,
)

selected_row = category_df[
    category_df["category"] == selected_category
].iloc[0]

selected_daily = daily_df[
    daily_df["category"] == selected_category
].copy()

selected_daily = selected_daily.sort_values(
    "datum"
)


# ============================================================================
# CATEGORY OVERVIEW
# ============================================================================

st.subheader(
    f"{selected_category} — Forecast Overview"
)

model_name = str(selected_row["model"])

recent_mean = float(
    selected_row["recent_30d_mean"]
)

forecast_mean = float(
    selected_row["forecast_30d_mean"]
)

forecast_change = float(
    selected_row["forecast_change_pct"]
)

mase = float(
    selected_row["MASE"]
)

status = str(
    selected_row["status"]
)


c1, c2, c3, c4, c5 = st.columns(5)

with c1:
    st.metric(
        "Selected Model",
        model_name,
    )

with c2:
    st.metric(
        "Recent 30-Day Mean",
        f"{recent_mean:.3f}",
    )

with c3:
    st.metric(
        "Forecast 30-Day Mean",
        f"{forecast_mean:.3f}",
    )

with c4:
    st.metric(
        "Forecast Change",
        f"{forecast_change:+.1f}%",
    )

with c5:
    st.metric(
        "MASE",
        f"{mase:.3f}",
    )


# ============================================================================
# STATUS
# ============================================================================

if status == "OK":

    st.success(
        "Status: OK — forecast is broadly aligned with recent demand."
    )

elif status == "MODERATE_CHANGE":

    st.warning(
        "Status: MODERATE CHANGE — forecast is materially different "
        "from recent demand and should be monitored."
    )

elif status == "INTERMITTENT_DEMAND_REVIEW":

    st.warning(
        "Status: INTERMITTENT DEMAND REVIEW — low-volume/intermittent "
        "demand requires additional review."
    )

else:

    st.info(
        f"Status: {status}"
    )


# ============================================================================
# FORECAST CHART
# ============================================================================

st.subheader("30-Day Forecast")

fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x=selected_daily["datum"],
        y=selected_daily["forecast"],
        mode="lines+markers",
        name="Forecast",
        line=dict(width=3),
        marker=dict(size=5),
    )
)

fig.add_hline(
    y=recent_mean,
    line_dash="dash",
    annotation_text="Recent 30-Day Mean",
    annotation_position="top left",
)

fig.add_hline(
    y=forecast_mean,
    line_dash="dot",
    annotation_text="Forecast Mean",
    annotation_position="bottom left",
)

fig.update_layout(
    height=500,
    xaxis_title="Date",
    yaxis_title="Forecast Demand",
    hovermode="x unified",
    legend=dict(
        orientation="h",
        yanchor="bottom",
        y=1.02,
        xanchor="right",
        x=1,
    ),
    margin=dict(
        l=40,
        r=40,
        t=60,
        b=40,
    ),
)

st.plotly_chart(
    fig,
    use_container_width=True,
)


# ============================================================================
# CATEGORY COMPARISON
# ============================================================================

st.divider()

st.subheader("Category Forecast Comparison")

comparison_df = category_df[
    [
        "category",
        "model",
        "recent_30d_mean",
        "forecast_30d_mean",
        "forecast_change_pct",
        "MASE",
        "status",
    ]
].copy()

comparison_df = comparison_df.sort_values(
    "forecast_change_pct",
    ascending=False,
)


fig_comparison = go.Figure()

fig_comparison.add_trace(
    go.Bar(
        x=comparison_df["category"],
        y=comparison_df["forecast_change_pct"],
        text=[
            f"{x:+.1f}%"
            for x in comparison_df["forecast_change_pct"]
        ],
        textposition="outside",
        name="Forecast Change",
    )
)

fig_comparison.add_hline(
    y=0,
    line_width=1,
)

fig_comparison.update_layout(
    height=450,
    xaxis_title="Category",
    yaxis_title="Forecast Change (%)",
    showlegend=False,
)

st.plotly_chart(
    fig_comparison,
    use_container_width=True,
)


# ============================================================================
# PERFORMANCE TABLE
# ============================================================================

st.subheader("Model Performance by Category")

performance_columns = [
    "category",
    "model",
    "MAE",
    "RMSE",
    "sMAPE",
    "WAPE",
    "MASE",
    "status",
]

performance_df = category_df[
    performance_columns
].copy()

for column in [
    "MAE",
    "RMSE",
    "sMAPE",
    "WAPE",
    "MASE",
]:

    performance_df[column] = performance_df[column].round(4)


st.dataframe(
    performance_df,
    use_container_width=True,
    hide_index=True,
)


# ============================================================================
# FLAGGED CATEGORIES
# ============================================================================

st.divider()

st.subheader("Categories Requiring Attention")

flagged_df = category_df[
    category_df["status"] != "OK"
].copy()

if flagged_df.empty:

    st.success(
        "No categories are currently flagged."
    )

else:

    st.dataframe(
        flagged_df[
            [
                "category",
                "model",
                "recent_30d_mean",
                "forecast_30d_mean",
                "forecast_change_pct",
                "MASE",
                "status",
            ]
        ].round(
            {
                "recent_30d_mean": 3,
                "forecast_30d_mean": 3,
                "forecast_change_pct": 2,
                "MASE": 3,
            }
        ),
        use_container_width=True,
        hide_index=True,
    )


# ============================================================================
# BUSINESS SUMMARY
# ============================================================================

st.divider()

st.subheader("Business Summary")

summary_col1, summary_col2 = st.columns(2)

with summary_col1:

    st.markdown(
        f"""
        **Forecast horizon:** {forecast_horizon} days

        **Total recent 30-day demand:** {total_recent:,.2f}

        **Total forecast demand:** {total_forecast:,.2f}

        **Overall forecast change:** {overall_change:+.2f}%
        """
    )

with summary_col2:

    st.markdown(
        f"""
        **Best MASE category:** {best_category}

        **Selected best model:** {best_model}

        **Flagged categories:** {flagged_categories}

        **Categories evaluated:** {total_categories}
        """
    )


# ============================================================================
# DATA PREVIEW
# ============================================================================

with st.expander("View forecast data"):

    st.dataframe(
        selected_daily,
        use_container_width=True,
        hide_index=True,
    )


st.caption(
    "PharmaInsight AI • Forecasts generated from the validated "
    "forecasting pipeline • Evaluation uses chronological "
    "out-of-sample testing."
)
