apiVersion: apps/v1
kind: Deployment
metadata:
  name: pharmainsight-frontend
  namespace: pharmainsight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pharmainsight-frontend
  template:
    metadata:
      labels:
        app: pharmainsight-frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/upasanadee/pharmainsight-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: pharmainsight-frontend
  namespace: pharmainsight
spec:
  selector:
    app: pharmainsight-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
