name: Kubernetes Validate

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    name: Validate Kubernetes manifests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install kubectl
        run: |
          curl -fsSL -o kubectl https://dl.k8s.io/release/v1.34.1/bin/linux/amd64/kubectl
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/kubectl

      - name: Validate Kubernetes manifests
        run: |
          kubectl apply --dry-run=client --validate=false \
            -f infrastructure/kubernetes/namespace.yaml

          kubectl apply --dry-run=client --validate=false \
            -f infrastructure/kubernetes/backend.yaml

          kubectl apply --dry-run=client --validate=false \
            -f infrastructure/kubernetes/frontend.yaml

          echo "Kubernetes manifests are valid."
